### GET Products

GET  http://localhost:5000/api/products/

### GET Product by id

GET  http://localhost:5000/api/products/b7a9451f-9b87-47b9-871c-b6bcfe367f38

### POST Products

POST http://localhost:5000/api/products/
Content-Type: application/json

{
    "title": "Anillo",
    "description": "Lorem ipsum",
    "price": 123,
    "stock": 40,
    "category": "Anillos",
    "thumbnail": "./assets/images/default.png"
}
